### ISSUE TITLE
fatal: unlinkat: permission denied

### ISSUE THREAD

**Issue by diorcula** [nicoleajoy/rose-pine-spotify#2]
Hello there,

Installing spicetify succeeded, but setting the theme didn't work as expected as i get thrown an fatal error.

I'm on Ubuntu 22.04 and just downloaded spotify and spicetify so they are of the latest update.

Here is the terminal output.
![image](https://user-images.githubusercontent.com/32682696/190638240-d955adbe-89c5-4dcc-b2af-c6fa8e53b51d.png)

Note: tried setting the theme for BurntSienna but got the same permission error.

**Comment by nicoleajoy** [comment]
Hello!

I looked through some issues from the spicetify-cli and spicetify-theme repos, and one of the possible solutions link to [this note from the installation page](https://spicetify.app/docs/advanced-usage/installation#note-for-linux-users), specifically for Linux users. Depending on how you installed Spotify (not spicetify), you may need to run one of the set of commands listed to gain permissions.

Let me know if this helps at all!

**Comment by diorcula** [comment]
Hello @nicoleajoy i checked out the solutions suggested but as i previously wrote these don't apply to me;

I did not install Spotify through snap but through the second option for Debian/Ubuntu:
![image](https://user-images.githubusercontent.com/32682696/190867385-f0390d2d-2bdc-41de-9b2a-1338678380eb.png)

I could always try to remove Spotify and re-install it through snap, but this is of course my least preferred method.

**Comment by diorcula** [comment]
@nicoleajoy I have tackled it again and found that you're answer was correct after all, my excuses.

The issue i had was that on Spicetify the option listed for Debian/Ubuntu installation was listed under Snap. And the answer was there as well.

![image](https://user-images.githubusercontent.com/32682696/191496040-5ff73b07-059c-45f9-8ec7-470640a57f32.png)

Thanks again, and have a great day!

**Comment by nicoleajoy** [comment]
Glad to hear it, have a lovely day as well! :-)
